/** Emit a TypeScript module from analyzed queries. */

import type { AnalyzedQuery, QueryColumn, QueryShape } from "./model.ts";
import type { QueryParam, SqlSegment } from "./params.ts";
import { camelCase, pascalCase } from "./naming.ts";
import {
  attrKey,
  tsForOid,
  typeNamesForOid,
  type TypeInfo,
  type TypeOverrides,
} from "./typemap.ts";
import type { CaseStyle } from "./config.ts";

export interface CodegenContext {
  typeInfo: TypeInfo;
  /** `${tableOid}:${attnum}` -> is NOT NULL. */
  notNull: Map<string, boolean>;
  /** Postgres type name -> TS type overrides. */
  overrides?: TypeOverrides;
  /** Import lines to emit at the top of the generated module. */
  imports?: string[];
  /** Postgres type name -> result hydration expression `(value) => T`. */
  parsers?: ReadonlyMap<string, string>;
  /** Postgres type name -> param serializer expression `(value: T) => unknown`. */
  serializers?: ReadonlyMap<string, string>;
  /** Postgres type name -> explicit runtime mode (`hydrate`/`none`). */
  runtime?: ReadonlyMap<string, string>;
  /** TypeScript field naming style for params and result rows. */
  caseStyle?: CaseStyle;
}

const HEADER = `// Code generated by genpg. DO NOT EDIT.
/* eslint-disable */`;

const RUNTIME = `export interface QueryResultLike {
  rows: any[];
  rowCount: number | null;
}

/**
 * Minimal interface satisfied by a node-postgres Client/Pool directly, or by an
 * adapter (see \`genpg/runtime\`) for other drivers such as postgres.js.
 */
export interface Queryable {
  query(text: string, values: unknown[]): Promise<QueryResultLike>;
}`;

export function generateModule(analyzed: AnalyzedQuery[], ctx: CodegenContext): string {
  validateGeneratedNames(analyzed);

  const blocks = [HEADER];
  if (ctx.imports && ctx.imports.length > 0) {
    blocks.push(ctx.imports.join("\n"));
  }
  blocks.push(RUNTIME);

  const converterConsts = renderConverterConsts(analyzed, ctx);
  if (converterConsts) blocks.push(converterConsts);

  blocks.push(...analyzed.map((a) => renderQuery(a, ctx)));
  blocks.push(renderBind(analyzed, ctx));
  return blocks.join("\n\n") + "\n";
}

/** Effective runtime mode for an overridden type name. */
function runtimeMode(name: string, ctx: CodegenContext): "hydrate" | "none" | undefined {
  const explicit = ctx.runtime?.get(name);
  if (explicit === "hydrate" || explicit === "none") return explicit;
  if (ctx.parsers?.has(name) || ctx.serializers?.has(name)) return "hydrate";
  return undefined;
}

/** True when a type's `parse` should hydrate result columns. */
function hydrates(name: string, ctx: CodegenContext): boolean {
  return ctx.parsers?.has(name) === true && runtimeMode(name, ctx) === "hydrate";
}

/** True when a type's `serialize` should wrap params. */
function serializes(name: string, ctx: CodegenContext): boolean {
  return ctx.serializers?.has(name) === true && runtimeMode(name, ctx) === "hydrate";
}

/** Module-level consts for each parse (result) / serialize (param) converter used. */
function renderConverterConsts(analyzed: AnalyzedQuery[], ctx: CodegenContext): string | null {
  const parseUsed = new Set<string>();
  const serializeUsed = new Set<string>();

  for (const a of analyzed) {
    if (a.query.command === "one" || a.query.command === "many") {
      for (const col of a.shape.columns ?? []) {
        const conv = columnConverter(col, ctx);
        if (conv) parseUsed.add(conv.name);
      }
    }
    for (const p of a.rewritten.params) {
      for (const oid of paramOids(p, a.shape)) {
        const ser = scalarSerializer(oid, ctx);
        if (ser) serializeUsed.add(ser.name);
      }
    }
  }

  const lines = [
    ...[...parseUsed].map((n) => `const ${parserConstName(n)} = ${ctx.parsers!.get(n)};`),
    ...[...serializeUsed].map(
      (n) => `const ${serializerConstName(n)} = ${ctx.serializers!.get(n)};`,
    ),
  ];
  return lines.length ? lines.join("\n") : null;
}

function renderQuery(a: AnalyzedQuery, ctx: CodegenContext): string {
  const pascal = pascalCase(a.query.name);
  const camel = camelCase(a.query.name);
  const sqlConst = `${camel}Sql`;
  const params = a.rewritten.params;
  const hasParams = params.length > 0;
  const wantsRows = a.query.command === "one" || a.query.command === "many";

  const out: string[] = [];
  if (!a.rewritten.dynamic) {
    out.push(`const ${sqlConst} = \`${escapeTemplate(a.rewritten.introspectText)}\`;`);
  }

  let argsType = "";
  if (hasParams) {
    argsType = `${pascal}Args`;
    const fields = params
      .map((p) => `  ${propName(tsFieldName(p.name, ctx))}: ${paramTsType(p, a.shape, ctx)};`)
      .join("\n");
    const doc = renderChildDoc(`Parameters for \`${camel}\`.`, a);
    out.push(`${doc}\nexport interface ${argsType} {\n${fields}\n}`);
  }

  let rowType = "";
  let hydrator: string | null = null;
  if (wantsRows) {
    rowType = `${pascal}Row`;
    const cols = a.shape.columns ?? [];
    const fields = cols
      .map((c, idx) => `  ${propName(tsFieldName(c.name, ctx))}: ${columnType(c, idx, a, ctx)};`)
      .join("\n");
    const doc = renderChildDoc(`Result row returned by \`${camel}\`.`, a);
    out.push(`${doc}\nexport interface ${rowType} {\n${fields || ""}\n}`);

    const built = renderHydrator(pascal, rowType, cols, ctx);
    if (built) {
      hydrator = built.name;
      out.push(built.decl);
    }
  }

  const sig = hasParams ? `db: Queryable, args: ${argsType}` : `db: Queryable`;
  const ret = returnType(a.query.command, rowType);
  const returnLine = returnExpr(a.query.command, rowType, hydrator);
  const body = a.rewritten.dynamic
    ? renderDynamicBody(a, ctx, returnLine)
    : renderStaticBody(a, ctx, sqlConst, returnLine);

  out.push(
    `${renderFunctionDoc(a, ctx)}\nexport async function ${camel}(${sig}): ${ret} {\n${body}\n}`,
  );
  return out.join("\n\n");
}

function renderFunctionDoc(a: AnalyzedQuery, ctx: CodegenContext, indent = ""): string {
  const lines = [];
  if (a.query.docs?.length) {
    lines.push(...a.query.docs, "");
  }
  lines.push(
    `Generated from \`${a.query.name} :${a.query.command}\`.`,
    "",
    "```sql",
    ...renderDocSql(a, ctx).split(/\r?\n/),
    "```",
  );
  if (a.query.deprecated) {
    lines.push("", `@deprecated ${a.query.deprecated}`);
  }
  return renderDocComment(lines, indent);
}

/**
 * The query as shown in hover docs, with each `@name` param rendered as a
 * `${name}` template slot.
 *
 * Two reasons for the slot form: TypeScript parses a whitespace-preceded `@` in a
 * doc comment as a JSDoc tag even inside a fenced code block, which truncates the
 * SQL at the first param; and the slot names use the generated field names, so
 * they match what the caller actually passes under `caseStyle: "camel"`.
 *
 * Built from the rewritten segments rather than the raw SQL so that `@` inside
 * string literals, comments, and dollar-quoted blocks is left alone.
 */
function renderDocSql(a: AnalyzedQuery, ctx: CodegenContext): string {
  return a.rewritten.segments
    .map((segment) => {
      if (typeof segment === "string") return segment;
      const param = a.rewritten.params[segment.param];
      return param ? `\${${tsFieldName(param.name, ctx)}}` : "";
    })
    .join("");
}

/** Doc for a query's generated `Args`/`Row` type, carrying any deprecation across. */
function renderChildDoc(summary: string, a: AnalyzedQuery): string {
  if (!a.query.deprecated) return `/** ${summary} */`;
  return renderDocComment([summary, "", `@deprecated ${a.query.deprecated}`]);
}

function renderDocComment(lines: string[], indent = ""): string {
  return ["/**", ...lines.map((line) => ` * ${escapeDocComment(line)}`), " */"]
    .map((line) => `${indent}${line}`)
    .join("\n");
}

function escapeDocComment(line: string): string {
  return line.replace(/\*\//g, "*\\/");
}

function renderBind(analyzed: AnalyzedQuery[], ctx: CodegenContext): string {
  const members: string[] = [];
  const entries: string[] = [];

  for (const a of analyzed) {
    const pascal = pascalCase(a.query.name);
    const camel = camelCase(a.query.name);
    const argsType = a.rewritten.params.length > 0 ? `${pascal}Args` : null;
    const wantsRows = a.query.command === "one" || a.query.command === "many";
    const ret = returnType(a.query.command, wantsRows ? `${pascal}Row` : "");

    const sig = argsType ? `(args: ${argsType})` : `()`;
    const call = argsType ? `${camel}(db, args)` : `${camel}(db)`;

    members.push(`${renderFunctionDoc(a, ctx, "  ")}\n  ${camel}${sig}: ${ret};`);
    entries.push(`    ${camel}: ${sig} => ${call},`);
  }

  return [
    `/** Every query bound to a single {@link Queryable}. */\nexport interface BoundQueries {\n${members.join("\n")}\n}`,
    `/** Bind every query to \`db\` so call sites don't have to pass it. */\nexport function bind(db: Queryable): BoundQueries {\n  return {\n${entries.join("\n")}\n  };\n}`,
  ].join("\n\n");
}

function returnType(command: AnalyzedQuery["query"]["command"], rowType: string): string {
  switch (command) {
    case "one":
      return `Promise<${rowType} | null>`;
    case "many":
      return `Promise<${rowType}[]>`;
    case "exec":
      return `Promise<void>`;
    case "execrows":
      return `Promise<number>`;
  }
}

/** The `return ...;` line, hydrating rows when a hydrator is present. */
function returnExpr(
  command: AnalyzedQuery["query"]["command"],
  rowType: string,
  hydrator: string | null,
) {
  return (resultVar: string): string => {
    switch (command) {
      case "one":
        return hydrator
          ? `  const row = ${resultVar}.rows[0];\n  return row ? ${hydrator}(row) : null;`
          : `  return (${resultVar}.rows[0] as ${rowType}) ?? null;`;
      case "many":
        return hydrator
          ? `  return ${resultVar}.rows.map(${hydrator});`
          : `  return ${resultVar}.rows as ${rowType}[];`;
      case "exec":
        return ``;
      case "execrows":
        return `  return ${resultVar}.rowCount ?? 0;`;
    }
  };
}

/** A per-query row hydrator converting overridden columns; null if none apply. */
function renderHydrator(
  pascal: string,
  rowType: string,
  cols: QueryColumn[],
  ctx: CodegenContext,
): { name: string; decl: string } | null {
  const mappings: string[] = [];
  const shouldMapAllFields = cols.some((col) => tsFieldName(col.name, ctx) !== col.name);

  for (const col of cols) {
    const conv = columnConverter(col, ctx);
    const access = rowAccess("r", col.name);
    let expr = access;
    if (conv) {
      const fn = parserConstName(conv.name);
      expr =
        conv.kind === "array"
          ? `${access} == null ? null : ${access}.map((e) => (e == null ? null : ${fn}(e)))`
          : `${access} == null ? null : ${fn}(${access})`;
    }
    if (shouldMapAllFields || conv) {
      mappings.push(`    ${propName(tsFieldName(col.name, ctx))}: ${expr},`);
    }
  }
  if (mappings.length === 0) return null;

  const name = `hydrate${pascal}Row`;
  const spread = shouldMapAllFields ? "" : "    ...r,\n";
  const decl =
    `function ${name}(r: any): ${rowType} {\n` +
    `  return {\n${spread}${mappings.join("\n")}\n  };\n}`;
  return { name, decl };
}

/** Does a result column hold a hydrate-parse type (scalar, or array of one)? */
function columnConverter(
  col: QueryColumn,
  ctx: CodegenContext,
): { kind: "scalar" | "array"; name: string } | null {
  const resolved = resolveDomain(col.typeOid, ctx.typeInfo);
  if (!resolved) return null;
  const own = ctx.typeInfo.types.get(col.typeOid)?.name;
  if (own && hydrates(own, ctx)) return { kind: "scalar", name: own };
  if (own && ctx.overrides?.has(own)) return null;
  if (resolved.type.typcategory === "A" && resolved.type.typelem) {
    const elem = converterNameForOid(resolved.type.typelem, ctx, hydrates);
    if (elem) return { kind: "array", name: elem };
  }
  const scalar = converterNameForOid(col.typeOid, ctx, hydrates);
  if (scalar) return { kind: "scalar", name: scalar };
  return null;
}

function renderStaticBody(
  a: AnalyzedQuery,
  ctx: CodegenContext,
  sqlConst: string,
  ret: (resultVar: string) => string,
): string {
  const values = a.rewritten.params.length
    ? `[${a.rewritten.params.map((p) => scalarValueExpr(rowAccess("args", tsFieldName(p.name, ctx)), paramOids(p, a.shape)[0] ?? 0, ctx)).join(", ")}]`
    : `[]`;

  if (a.query.command === "exec") {
    return `  await db.query(${sqlConst}, ${values});`;
  }
  return `  const result = await db.query(${sqlConst}, ${values});\n${ret("result")}`;
}

/** Build SQL + values at runtime for queries with array/spread params. */
function renderDynamicBody(
  a: AnalyzedQuery,
  ctx: CodegenContext,
  ret: (resultVar: string) => string,
): string {
  const lines: string[] = [];

  // Empty arrays would produce invalid `VALUES ` for spreads: short-circuit.
  for (const p of a.rewritten.params) {
    if (p.kind === "spread") {
      lines.push(
        `  if (${rowAccess("args", tsFieldName(p.name, ctx))}.length === 0) ${emptyReturn(a.query.command)}`,
      );
    }
  }

  lines.push(`  const values: unknown[] = [];`);
  lines.push(`  let _i = 0;`);

  a.rewritten.params.forEach((p, idx) => {
    lines.push(...renderParamFragment(p, idx, a, ctx));
  });

  lines.push(`  const text = ${assembleText(a.rewritten.segments)};`);

  if (a.query.command === "exec") {
    lines.push(`  await db.query(text, values);`);
  } else {
    lines.push(`  const result = await db.query(text, values);`);
    lines.push(ret("result"));
  }
  return lines.join("\n");
}

/** Emit `const _p<idx> = ...;` building one parameter's SQL fragment + values. */
function renderParamFragment(
  p: QueryParam,
  idx: number,
  a: AnalyzedQuery,
  ctx: CodegenContext,
): string[] {
  const oids = paramOids(p, a.shape);
  const v = `_p${idx}`;

  if (p.kind === "scalar") {
    const value = scalarValueExpr(rowAccess("args", tsFieldName(p.name, ctx)), oids[0] ?? 0, ctx);
    return [`  const ${v} = (() => { values.push(${value}); return \`$\${++_i}\`; })();`];
  }

  if (p.kind === "array") {
    const elem = scalarValueExpr("v", oids[0] ?? 0, ctx);
    return [
      `  const ${v} = (() => {`,
      `    const xs = ${rowAccess("args", tsFieldName(p.name, ctx))};`,
      `    if (xs.length === 0) return "(NULL)";`,
      `    return "(" + xs.map((v) => { values.push(${elem}); return \`$\${++_i}\`; }).join(", ") + ")";`,
      `  })();`,
    ];
  }

  // spread
  const fields = p.fields ?? [];
  const pushes = fields
    .map((f, i) => {
      const value = scalarValueExpr(rowAccess("r", tsFieldName(f, ctx)), oids[i] ?? 0, ctx);
      return `      values.push(${value}); slots.push(\`$\${++_i}\`);`;
    })
    .join("\n");
  return [
    `  const ${v} = (() => {`,
    `    const tuples: string[] = [];`,
    `    for (const r of ${rowAccess("args", tsFieldName(p.name, ctx))}) {`,
    `      const slots: string[] = [];`,
    pushes,
    `      tuples.push("(" + slots.join(", ") + ")");`,
    `    }`,
    `    return tuples.join(", ");`,
    `  })();`,
  ];
}

function assembleText(segments: SqlSegment[]): string {
  let t = "`";
  for (const seg of segments) {
    t += typeof seg === "string" ? escapeTemplate(seg) : "${_p" + seg.param + "}";
  }
  return t + "`";
}

function emptyReturn(command: AnalyzedQuery["query"]["command"]): string {
  switch (command) {
    case "one":
      return `return null;`;
    case "many":
      return `return [];`;
    case "exec":
      return `return;`;
    case "execrows":
      return `return 0;`;
  }
}

function paramOids(p: QueryParam, shape: QueryShape): number[] {
  return p.placeholders.map((ph) => shape.params[ph - 1] ?? 0);
}

function paramTsType(p: QueryParam, shape: QueryShape, ctx: CodegenContext): string {
  const oids = paramOids(p, shape);
  if (p.kind === "scalar") {
    const base = tsForOid(oids[0] ?? 0, ctx.typeInfo, ctx.overrides);
    return p.nullable ? `${base} | null` : base;
  }
  if (p.kind === "array") {
    const base = tsForOid(oids[0] ?? 0, ctx.typeInfo, ctx.overrides);
    return /[|&]/.test(base) ? `(${base})[]` : `${base}[]`;
  }
  const entries = (p.fields ?? []).map(
    (f, i) =>
      `${propName(tsFieldName(f, ctx))}: ${tsForOid(oids[i] ?? 0, ctx.typeInfo, ctx.overrides)}`,
  );
  return `{ ${entries.join("; ")} }[]`;
}

/** A value expression for a scalar, wrapped with a serializer when configured. */
function scalarValueExpr(access: string, oid: number, ctx: CodegenContext): string {
  const ser = scalarSerializer(oid, ctx);
  if (!ser) return access;
  if (ser.kind === "array") {
    return `${access} == null ? null : ${access}.map((e) => (e == null ? null : ${ser.fn}(e)))`;
  }
  return `${access} == null ? null : ${ser.fn}(${access})`;
}

function scalarSerializer(
  oid: number,
  ctx: CodegenContext,
): { kind: "scalar" | "array"; name: string; fn: string } | null {
  const resolved = resolveDomain(oid, ctx.typeInfo);
  if (!resolved) return null;
  const own = ctx.typeInfo.types.get(oid)?.name;
  if (own && serializes(own, ctx)) {
    return { kind: "scalar", name: own, fn: serializerConstName(own) };
  }
  if (own && ctx.overrides?.has(own)) return null;
  if (resolved.type.typcategory === "A" && resolved.type.typelem) {
    const elem = converterNameForOid(resolved.type.typelem, ctx, serializes);
    if (elem) {
      return { kind: "array", name: elem, fn: serializerConstName(elem) };
    }
  }
  const scalar = converterNameForOid(oid, ctx, serializes);
  if (scalar) return { kind: "scalar", name: scalar, fn: serializerConstName(scalar) };
  return null;
}

function converterNameForOid(
  oid: number,
  ctx: CodegenContext,
  hasConverter: (name: string, ctx: CodegenContext) => boolean,
): string | undefined {
  for (const name of typeNamesForOid(oid, ctx.typeInfo)) {
    if (hasConverter(name, ctx)) return name;
    if (ctx.overrides?.has(name)) return undefined;
  }
  return undefined;
}

function resolveDomain(
  oid: number,
  info: TypeInfo,
  depth = 0,
): { oid: number; type: NonNullable<ReturnType<TypeInfo["types"]["get"]>> } | null {
  if (oid === 0 || depth > 16) return null;
  const t = info.types.get(oid);
  if (!t) return null;
  if (t.typtype === "d" && t.typbasetype) return resolveDomain(t.typbasetype, info, depth + 1);
  return { oid, type: t };
}

function columnType(
  col: QueryColumn,
  idx: number,
  analyzed: AnalyzedQuery,
  ctx: CodegenContext,
): string {
  const base = tsForOid(col.typeOid, ctx.typeInfo, ctx.overrides);
  const known = col.tableOid > 0 && col.columnAttr > 0;
  const isNotNull =
    analyzed.inferredNotNullColumns?.has(idx) === true ||
    (known && ctx.notNull.get(attrKey(col.tableOid, col.columnAttr)) === true);
  return isNotNull ? base : `${base} | null`;
}

function serializerConstName(typeName: string): string {
  return "__ser_" + typeName.replace(/[^A-Za-z0-9_]/g, "_");
}

function parserConstName(typeName: string): string {
  return "__parse_" + typeName.replace(/[^A-Za-z0-9_]/g, "_");
}

function tsFieldName(name: string, ctx: CodegenContext): string {
  return ctx.caseStyle === "camel" ? camelCase(name) : name;
}

/** Quote a result-column name as an object key if it isn't a plain identifier. */
function propName(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

/** Property access on `obj` for a possibly-non-identifier column name. */
function rowAccess(obj: string, name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)
    ? `${obj}.${name}`
    : `${obj}[${JSON.stringify(name)}]`;
}

/** Escape a SQL string for embedding inside a TS template literal. */
function escapeTemplate(sql: string): string {
  return sql.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function validateGeneratedNames(analyzed: AnalyzedQuery[]): void {
  const used = new Map<string, string>();
  for (const name of MODULE_IDENTIFIERS) used.set(name, "a genpg module-level declaration");

  for (const a of analyzed) {
    const source = `query "${a.query.name}"`;
    const pascal = pascalCase(a.query.name);
    const camel = camelCase(a.query.name);
    const identifiers: [string, string][] = [[camel, `${source} function`]];
    if (!a.rewritten.dynamic) identifiers.push([`${camel}Sql`, `${source} SQL constant`]);
    if (a.rewritten.params.length > 0) identifiers.push([`${pascal}Args`, `${source} args type`]);
    if (a.query.command === "one" || a.query.command === "many") {
      identifiers.push([`${pascal}Row`, `${source} row type`]);
    }

    for (const [identifier, label] of identifiers) {
      assertTsIdentifier(identifier, label);
      const previous = used.get(identifier);
      if (previous) {
        throw new Error(
          `Generated identifier "${identifier}" for ${label} collides with ${previous}. ` +
            `Rename one of the queries.`,
        );
      }
      used.set(identifier, label);
    }
  }
}

/** Names genpg always emits at module scope; queries may not shadow them. */
const MODULE_IDENTIFIERS = ["QueryResultLike", "Queryable", "BoundQueries", "bind"];

function assertTsIdentifier(identifier: string, label: string): void {
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(identifier) || RESERVED_TS_WORDS.has(identifier)) {
    throw new Error(
      `Generated identifier "${identifier}" for ${label} is not a valid TypeScript identifier. ` +
        `Rename the query.`,
    );
  }
}

const RESERVED_TS_WORDS = new Set([
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "new",
  "null",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "as",
  "implements",
  "interface",
  "let",
  "package",
  "private",
  "protected",
  "public",
  "static",
  "yield",
]);
