/** Emit a TypeScript module from analyzed queries. */

import type { AnalyzedQuery, QueryColumn, QueryShape } from "./model.ts";
import type { QueryParam, SqlSegment } from "./params.ts";
import { camelCase, pascalCase } from "./naming.ts";
import { attrKey, tsForOid, type TypeInfo, type TypeOverrides } from "./typemap.ts";
import type { CaseStyle } from "./config.ts";

export interface CodegenContext {
  typeInfo: TypeInfo;
  /** `${tableOid}:${attnum}` -> is NOT NULL. */
  notNull: Map<string, boolean>;
  /** Postgres type name -> TS type overrides. */
  overrides?: TypeOverrides;
  /** Import lines to emit at the top of the generated module. */
  imports?: string[];
  /** Postgres type name -> result hydration expression `(value) => T`. */
  parsers?: ReadonlyMap<string, string>;
  /** Postgres type name -> param serializer expression `(value: T) => unknown`. */
  serializers?: ReadonlyMap<string, string>;
  /** Postgres type name -> explicit runtime mode (`hydrate`/`none`). */
  runtime?: ReadonlyMap<string, string>;
  /** TypeScript field naming style for params and result rows. */
  caseStyle?: CaseStyle;
}

const HEADER = `// Code generated by genpg. DO NOT EDIT.
/* eslint-disable */`;

const RUNTIME = `export interface QueryResultLike {
  rows: any[];
  rowCount: number | null;
}

/**
 * Minimal interface satisfied by a node-postgres Client/Pool directly, or by an
 * adapter (see \`genpg/runtime\`) for other drivers such as postgres.js.
 */
export interface Queryable {
  query(text: string, values: unknown[]): Promise<QueryResultLike>;
}`;

export function generateModule(analyzed: AnalyzedQuery[], ctx: CodegenContext): string {
  const blocks = [HEADER];
  if (ctx.imports && ctx.imports.length > 0) {
    blocks.push(ctx.imports.join("\n"));
  }
  blocks.push(RUNTIME);

  const converterConsts = renderConverterConsts(analyzed, ctx);
  if (converterConsts) blocks.push(converterConsts);

  blocks.push(...analyzed.map((a) => renderQuery(a, ctx)));
  blocks.push(renderBind(analyzed));
  return blocks.join("\n\n") + "\n";
}

/** Effective runtime mode for an overridden type name. */
function runtimeMode(name: string, ctx: CodegenContext): "hydrate" | "none" | undefined {
  const explicit = ctx.runtime?.get(name);
  if (explicit === "hydrate" || explicit === "none") return explicit;
  if (ctx.parsers?.has(name) || ctx.serializers?.has(name)) return "hydrate";
  return undefined;
}

/** True when a type's `parse` should hydrate result columns. */
function hydrates(name: string, ctx: CodegenContext): boolean {
  return ctx.parsers?.has(name) === true && runtimeMode(name, ctx) === "hydrate";
}

/** True when a type's `serialize` should wrap params. */
function serializes(name: string, ctx: CodegenContext): boolean {
  return ctx.serializers?.has(name) === true && runtimeMode(name, ctx) === "hydrate";
}

/** Module-level consts for each parse (result) / serialize (param) converter used. */
function renderConverterConsts(analyzed: AnalyzedQuery[], ctx: CodegenContext): string | null {
  const parseUsed = new Set<string>();
  const serializeUsed = new Set<string>();

  for (const a of analyzed) {
    if (a.query.command === "one" || a.query.command === "many") {
      for (const col of a.shape.columns ?? []) {
        for (const name of typeNamesForOid(col.typeOid, ctx.typeInfo)) {
          if (hydrates(name, ctx)) parseUsed.add(name);
        }
      }
    }
    for (const p of a.rewritten.params) {
      for (const oid of paramOids(p, a.shape)) {
        for (const name of typeNamesForOid(oid, ctx.typeInfo)) {
          if (serializes(name, ctx)) serializeUsed.add(name);
        }
      }
    }
  }

  const lines = [
    ...[...parseUsed].map((n) => `const ${parserConstName(n)} = ${ctx.parsers!.get(n)};`),
    ...[...serializeUsed].map(
      (n) => `const ${serializerConstName(n)} = ${ctx.serializers!.get(n)};`,
    ),
  ];
  return lines.length ? lines.join("\n") : null;
}

/** A type name plus, for arrays, its element type name. */
function typeNamesForOid(oid: number, info: TypeInfo): string[] {
  const t = info.types.get(oid);
  if (!t) return [];
  const names = [t.name];
  if (t.typcategory === "A" && t.typelem) {
    const el = info.types.get(t.typelem);
    if (el) names.push(el.name);
  }
  return names;
}

function renderQuery(a: AnalyzedQuery, ctx: CodegenContext): string {
  const pascal = pascalCase(a.query.name);
  const camel = camelCase(a.query.name);
  const sqlConst = `${camel}Sql`;
  const params = a.rewritten.params;
  const hasParams = params.length > 0;
  const wantsRows = a.query.command === "one" || a.query.command === "many";

  const out: string[] = [];
  if (!a.rewritten.dynamic) {
    out.push(`const ${sqlConst} = \`${escapeTemplate(a.rewritten.introspectText)}\`;`);
  }

  let argsType = "";
  if (hasParams) {
    argsType = `${pascal}Args`;
    const fields = params
      .map((p) => `  ${propName(tsFieldName(p.name, ctx))}: ${paramTsType(p, a.shape, ctx)};`)
      .join("\n");
    out.push(`export interface ${argsType} {\n${fields}\n}`);
  }

  let rowType = "";
  let hydrator: string | null = null;
  if (wantsRows) {
    rowType = `${pascal}Row`;
    const cols = a.shape.columns ?? [];
    const fields = cols
      .map((c, idx) => `  ${propName(tsFieldName(c.name, ctx))}: ${columnType(c, idx, a, ctx)};`)
      .join("\n");
    out.push(`export interface ${rowType} {\n${fields || ""}\n}`);

    const built = renderHydrator(pascal, rowType, cols, ctx);
    if (built) {
      hydrator = built.name;
      out.push(built.decl);
    }
  }

  const sig = hasParams ? `db: Queryable, args: ${argsType}` : `db: Queryable`;
  const ret = returnType(a.query.command, rowType);
  const returnLine = returnExpr(a.query.command, rowType, hydrator);
  const body = a.rewritten.dynamic
    ? renderDynamicBody(a, ctx, returnLine)
    : renderStaticBody(a, ctx, sqlConst, returnLine);

  out.push(`export async function ${camel}(${sig}): ${ret} {\n${body}\n}`);
  return out.join("\n\n");
}

function renderBind(analyzed: AnalyzedQuery[]): string {
  const entries = analyzed.map((a) => {
    const camel = camelCase(a.query.name);
    const argsType = a.rewritten.params.length > 0 ? `${pascalCase(a.query.name)}Args` : null;
    const sig = argsType ? `(args: ${argsType})` : `()`;
    const call = argsType ? `${camel}(db, args)` : `${camel}(db)`;
    return `    ${camel}: ${sig} => ${call},`;
  });

  return `export function bind(db: Queryable) {\n  return {\n${entries.join("\n")}\n  };\n}`;
}

function returnType(command: AnalyzedQuery["query"]["command"], rowType: string): string {
  switch (command) {
    case "one":
      return `Promise<${rowType} | null>`;
    case "many":
      return `Promise<${rowType}[]>`;
    case "exec":
      return `Promise<void>`;
    case "execrows":
      return `Promise<number>`;
  }
}

/** The `return ...;` line, hydrating rows when a hydrator is present. */
function returnExpr(
  command: AnalyzedQuery["query"]["command"],
  rowType: string,
  hydrator: string | null,
) {
  return (resultVar: string): string => {
    switch (command) {
      case "one":
        return hydrator
          ? `  const row = ${resultVar}.rows[0];\n  return row ? ${hydrator}(row) : null;`
          : `  return (${resultVar}.rows[0] as ${rowType}) ?? null;`;
      case "many":
        return hydrator
          ? `  return ${resultVar}.rows.map(${hydrator});`
          : `  return ${resultVar}.rows as ${rowType}[];`;
      case "exec":
        return ``;
      case "execrows":
        return `  return ${resultVar}.rowCount ?? 0;`;
    }
  };
}

/** A per-query row hydrator converting overridden columns; null if none apply. */
function renderHydrator(
  pascal: string,
  rowType: string,
  cols: QueryColumn[],
  ctx: CodegenContext,
): { name: string; decl: string } | null {
  const mappings: string[] = [];
  const shouldMapAllFields = cols.some((col) => tsFieldName(col.name, ctx) !== col.name);

  for (const col of cols) {
    const conv = columnConverter(col, ctx);
    const access = rowAccess("r", col.name);
    let expr = access;
    if (conv) {
      const fn = parserConstName(conv.name);
      expr =
        conv.kind === "array"
          ? `${access} == null ? null : ${access}.map((e) => (e == null ? null : ${fn}(e)))`
          : `${access} == null ? null : ${fn}(${access})`;
    }
    if (shouldMapAllFields || conv) {
      mappings.push(`    ${propName(tsFieldName(col.name, ctx))}: ${expr},`);
    }
  }
  if (mappings.length === 0) return null;

  const name = `hydrate${pascal}Row`;
  const spread = shouldMapAllFields ? "" : "    ...r,\n";
  const decl =
    `function ${name}(r: any): ${rowType} {\n` +
    `  return {\n${spread}${mappings.join("\n")}\n  };\n}`;
  return { name, decl };
}

/** Does a result column hold a hydrate-parse type (scalar, or array of one)? */
function columnConverter(
  col: QueryColumn,
  ctx: CodegenContext,
): { kind: "scalar" | "array"; name: string } | null {
  const t = ctx.typeInfo.types.get(col.typeOid);
  if (!t) return null;
  if (hydrates(t.name, ctx)) return { kind: "scalar", name: t.name };
  if (t.typcategory === "A" && t.typelem) {
    const el = ctx.typeInfo.types.get(t.typelem);
    if (el && hydrates(el.name, ctx)) return { kind: "array", name: el.name };
  }
  return null;
}

function renderStaticBody(
  a: AnalyzedQuery,
  ctx: CodegenContext,
  sqlConst: string,
  ret: (resultVar: string) => string,
): string {
  const values = a.rewritten.params.length
    ? `[${a.rewritten.params.map((p) => scalarValueExpr(rowAccess("args", tsFieldName(p.name, ctx)), paramOids(p, a.shape)[0] ?? 0, ctx)).join(", ")}]`
    : `[]`;

  if (a.query.command === "exec") {
    return `  await db.query(${sqlConst}, ${values});`;
  }
  return `  const result = await db.query(${sqlConst}, ${values});\n${ret("result")}`;
}

/** Build SQL + values at runtime for queries with array/spread params. */
function renderDynamicBody(
  a: AnalyzedQuery,
  ctx: CodegenContext,
  ret: (resultVar: string) => string,
): string {
  const lines: string[] = [];

  // Empty arrays would produce invalid `VALUES ` for spreads: short-circuit.
  for (const p of a.rewritten.params) {
    if (p.kind === "spread") {
      lines.push(
        `  if (${rowAccess("args", tsFieldName(p.name, ctx))}.length === 0) ${emptyReturn(a.query.command)}`,
      );
    }
  }

  lines.push(`  const values: unknown[] = [];`);
  lines.push(`  let _i = 0;`);

  a.rewritten.params.forEach((p, idx) => {
    lines.push(...renderParamFragment(p, idx, a, ctx));
  });

  lines.push(`  const text = ${assembleText(a.rewritten.segments)};`);

  if (a.query.command === "exec") {
    lines.push(`  await db.query(text, values);`);
  } else {
    lines.push(`  const result = await db.query(text, values);`);
    lines.push(ret("result"));
  }
  return lines.join("\n");
}

/** Emit `const _p<idx> = ...;` building one parameter's SQL fragment + values. */
function renderParamFragment(
  p: QueryParam,
  idx: number,
  a: AnalyzedQuery,
  ctx: CodegenContext,
): string[] {
  const oids = paramOids(p, a.shape);
  const v = `_p${idx}`;

  if (p.kind === "scalar") {
    const value = scalarValueExpr(rowAccess("args", tsFieldName(p.name, ctx)), oids[0] ?? 0, ctx);
    return [`  const ${v} = (() => { values.push(${value}); return \`$\${++_i}\`; })();`];
  }

  if (p.kind === "array") {
    const elem = scalarValueExpr("v", oids[0] ?? 0, ctx);
    return [
      `  const ${v} = (() => {`,
      `    const xs = ${rowAccess("args", tsFieldName(p.name, ctx))};`,
      `    if (xs.length === 0) return "(NULL)";`,
      `    return "(" + xs.map((v) => { values.push(${elem}); return \`$\${++_i}\`; }).join(", ") + ")";`,
      `  })();`,
    ];
  }

  // spread
  const fields = p.fields ?? [];
  const pushes = fields
    .map((f, i) => {
      const value = scalarValueExpr(rowAccess("r", tsFieldName(f, ctx)), oids[i] ?? 0, ctx);
      return `      values.push(${value}); slots.push(\`$\${++_i}\`);`;
    })
    .join("\n");
  return [
    `  const ${v} = (() => {`,
    `    const tuples: string[] = [];`,
    `    for (const r of ${rowAccess("args", tsFieldName(p.name, ctx))}) {`,
    `      const slots: string[] = [];`,
    pushes,
    `      tuples.push("(" + slots.join(", ") + ")");`,
    `    }`,
    `    return tuples.join(", ");`,
    `  })();`,
  ];
}

function assembleText(segments: SqlSegment[]): string {
  let t = "`";
  for (const seg of segments) {
    t += typeof seg === "string" ? escapeTemplate(seg) : "${_p" + seg.param + "}";
  }
  return t + "`";
}

function emptyReturn(command: AnalyzedQuery["query"]["command"]): string {
  switch (command) {
    case "one":
      return `return null;`;
    case "many":
      return `return [];`;
    case "exec":
      return `return;`;
    case "execrows":
      return `return 0;`;
  }
}

function paramOids(p: QueryParam, shape: QueryShape): number[] {
  return p.placeholders.map((ph) => shape.params[ph - 1] ?? 0);
}

function paramTsType(p: QueryParam, shape: QueryShape, ctx: CodegenContext): string {
  const oids = paramOids(p, shape);
  if (p.kind === "scalar") {
    const base = tsForOid(oids[0] ?? 0, ctx.typeInfo, ctx.overrides);
    return p.nullable ? `${base} | null` : base;
  }
  if (p.kind === "array") {
    const base = tsForOid(oids[0] ?? 0, ctx.typeInfo, ctx.overrides);
    return /[|&]/.test(base) ? `(${base})[]` : `${base}[]`;
  }
  const entries = (p.fields ?? []).map(
    (f, i) =>
      `${propName(tsFieldName(f, ctx))}: ${tsForOid(oids[i] ?? 0, ctx.typeInfo, ctx.overrides)}`,
  );
  return `{ ${entries.join("; ")} }[]`;
}

/** A value expression for a scalar, wrapped with a serializer when configured. */
function scalarValueExpr(access: string, oid: number, ctx: CodegenContext): string {
  const ser = scalarSerializer(oid, ctx);
  return ser ? `${access} == null ? null : ${ser}(${access})` : access;
}

function scalarSerializer(oid: number, ctx: CodegenContext): string | null {
  const t = ctx.typeInfo.types.get(oid);
  return t && serializes(t.name, ctx) ? serializerConstName(t.name) : null;
}

function columnType(
  col: QueryColumn,
  idx: number,
  analyzed: AnalyzedQuery,
  ctx: CodegenContext,
): string {
  const base = tsForOid(col.typeOid, ctx.typeInfo, ctx.overrides);
  const known = col.tableOid > 0 && col.columnAttr > 0;
  const isNotNull =
    analyzed.inferredNotNullColumns?.has(idx) === true ||
    (known && ctx.notNull.get(attrKey(col.tableOid, col.columnAttr)) === true);
  return isNotNull ? base : `${base} | null`;
}

function serializerConstName(typeName: string): string {
  return "__ser_" + typeName.replace(/[^A-Za-z0-9_]/g, "_");
}

function parserConstName(typeName: string): string {
  return "__parse_" + typeName.replace(/[^A-Za-z0-9_]/g, "_");
}

function tsFieldName(name: string, ctx: CodegenContext): string {
  return ctx.caseStyle === "camel" ? camelCase(name) : name;
}

/** Quote a result-column name as an object key if it isn't a plain identifier. */
function propName(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

/** Property access on `obj` for a possibly-non-identifier column name. */
function rowAccess(obj: string, name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)
    ? `${obj}.${name}`
    : `${obj}[${JSON.stringify(name)}]`;
}

/** Escape a SQL string for embedding inside a TS template literal. */
function escapeTemplate(sql: string): string {
  return sql.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}
